[package]
name = "coolgame"
version = "0.1.0"
edition = "2021"

# See more keys and their definitions at https://doc.rust-lang.org/cargo/reference/manifest.html

[dependencies]
laminar = "0.5"
crossbeam-channel = "0.5.6"
bevy = "0.9.1"
bevy_egui = "0.19"